### ISSUE TITLE
Ajustes para API de configuración

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#5]
La organización requiere que el API de configuración sea desplegado contemplando los **cambios hechos** sobre el modelo de datos de dicho componente, y planeando el periodo de transición de dicho API de ser necesario.

**Criterios de aceptación:**
- [x] Cambios en repositorio del API.
- [x] API desplegado en ambiente Cloud.

> Referenciar dichos cambios mediante el uso de `udistrital/notificacion_api#5`

**Comment by fabianLeon** [comment]
se ajustó estructura de api para nuevo modelo de notificaciones [b5d7abce](https://github.com/udistrital/configuracion_api/commit/b5d7abce2f96acbf0edcc5095ea89521c53af0bb) y [8d31ea98](https://github.com/udistrital/configuracion_api/commit/8d31ea9802482164d595291f9a2b39e9c1b355d7)

**Comment by fabianLeon** [comment]
se realiza ajuste para despliegue en ambiente test con [commit](https://github.com/udistrital/configuracion_api/commit/49137f53fa009b3469ec571275bf2227801643cc) pero presenta un error en el [ci de drone](https://ci.portaloas.udistrital.edu.co/udistrital/configuracion_api/69).

se realiza revisión del repo de cloudFormation y se evidencia que existe el servicio.

```
  ServiceConfiguracionApiTest:
      Type: AWS::ECS::Service
      Properties:
        Cluster: test
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 100
        DesiredCount: 1
        HealthCheckGracePeriodSeconds: 120
        LaunchType: EC2
        LoadBalancers:
          - ContainerName: configuracion_api
            ContainerPort: 8080
            TargetGroupArn:
              Ref: TargetGroupConfiguracionApiTest
        Role:
          Ref: RoleServicesOas
        ServiceName: configuracion_api_test
        TaskDefinition:
          Ref: TaskDefinitionConfiguracionApiTest
```

aunque el error que arroja el ci es 
```
+ AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} AWS_REGION=$AWS_REGION $GOPATH/bin/update-aws-ecs-service -cluster $CLUSTER -service $SERVICE -container-image $container_name=$MYCONTAINER
2019/06/26 19:33:02 the service does not exist
```
